CREATE TABLE Subscription (
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    endpoint VARCHAR(500) NOT NULL UNIQUE,
    contentEncoding VARCHAR(500) NOT NULL,
    authToken VARCHAR(500) NOT NULL,
    publicKey VARCHAR(500) NOT NULL
);